# Generated by Django 4.0.2 on 2024-02-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('student_num', models.CharField(max_length=30, verbose_name='학번')),
                ('grade', models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년'), ('4', '4학년')], default='1', max_length=10, verbose_name='학년')),
                ('phone_num', models.CharField(max_length=20, verbose_name='휴대폰 번호')),
                ('first_major', models.CharField(max_length=30, verbose_name='본전공')),
                ('second_major', models.CharField(blank=True, max_length=30, null=True, verbose_name='이중전공')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='합격 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
