# Generated by Django 4.0.2 on 2024-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Is additional'),
        ),
    ]
