# Generated by Django 4.0.2 on 2024-02-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='추가 모집'),
        ),
    ]
